document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
document.writeln("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">");
document.writeln("    <title>Document</title>");
document.writeln("    <link rel=\"stylesheet\" href=\"css/reset.css\">");
document.writeln("    <link rel=\"stylesheet\" href=\"css/footer.css\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\"footer-info-w\">");
document.writeln("        <div class=\"footer-info-content-wrap\">");
document.writeln("            <ul class=\"footer-info-content-list clearfix\">");
document.writeln("                <li class=\"clearfix\">");
document.writeln("                    <div>");
document.writeln("                        <i class=\"footer-info-bgimg-one\"></i>");
document.writeln("                        <p>顺丰EMS速达</p>");
document.writeln("                    </div>");
document.writeln("                    <span>|</span>");
document.writeln("                </li>");
document.writeln("                <li class=\"clearfix\">");
document.writeln("                    <div>");
document.writeln("                        <i class=\"footer-info-bgimg-two\"></i>");
document.writeln("                        <p>丰富礼赠</p>");
document.writeln("                    </div>");
document.writeln("                    <span>|</span>");
document.writeln("                </li>");
document.writeln("                <li class=\"clearfix\">");
document.writeln("                    <div>");
document.writeln("                        <i class=\"footer-info-bgimg-three\"></i>");
document.writeln("                        <p>100%官方正品</p>");
document.writeln("                    </div>");
document.writeln("                    <span>|</span>");
document.writeln("                </li>");
document.writeln("                <li class=\"clearfix\">");
document.writeln("                    <div>");
document.writeln("                        <i class=\"footer-info-bgimg-four\"></i>");
document.writeln("                        <p>无障碍退款</p>");
document.writeln("                    </div>");
document.writeln("                    <span>|</span>");
document.writeln("                </li>");
document.writeln("                <li class=\"clearfix\">");
document.writeln("                    <div>");
document.writeln("                        <i class=\"footer-info-bgimg-five\"></i>");
document.writeln("                        <p>安全支付</p>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    ");
document.writeln("        <!-- footer-info-content -->");
document.writeln("        <div class=\"footer-map-content\">");
document.writeln("            <ul class=\"footer-map-content-list clearfix\">");
document.writeln("                <li>");
document.writeln("                    <h3>购物流程</h3>");
document.writeln("                    <p><a href=\"###\">大宗采购/团购</a></p>");
document.writeln("                    <p><a href=\"###\">丝芙兰预付卡章程</a></p>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <h3>支付/配送</h3>");
document.writeln("                    <p><a href=\"###\">货到付款</a></p>");
document.writeln("                    <p><a href=\"###\">在线支付</a></p>");
document.writeln("                    <p><a href=\"###\">配送时间</a></p>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <h3>售后服务</h3>");
document.writeln("                    <p><a href=\"###\">退换货规定</a></p>");
document.writeln("                    <p><a href=\"###\">退换货及退款说明</a></p>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <h3>关于丝芙兰</h3>");
document.writeln("                    <p><a href=\"###\">公司介绍</a></p>");
document.writeln("                    <p><a href=\"###\">联系我们</a></p>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <h3><a href=\"###\">网上订购咨询热线 : 400 670 0055</a></h3>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!-- footer-map-content -->");
document.writeln("    </div>");
document.writeln("    <div class=\"footer-declaration-content\">");
document.writeln("        <div class=\"footer-declaration-content-wrap clearfix\">");
document.writeln("            <ul>");
document.writeln("                <li>");
document.writeln("                    <a href=\"###\" class=\"footer-declaration-content-bgimg\">沪公网安备 31010102003277号</a>");
document.writeln("                    <a href=\"###\">ICP备案序号:沪ICP备05026645号</a>");
document.writeln("                    <a href=\"###\">网站使用条款</a>");
document.writeln("                    <a href=\"###\">严正声明</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    本网站隶属于丝芙兰（上海）化妆品销售有限公司");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("            <img src=\"images/footer_cxsf.png\" alt=\"\">");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</body>");
document.writeln("</html>");